"""add_anomalies_table

Revision ID: 1700e9b98c6d
Revises: 70aaac4d598a
Create Date: 2026-06-26 16:15:54.947867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1700e9b98c6d'
down_revision: Union[str, Sequence[str], None] = '70aaac4d598a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book', sa.String(length=50), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('verse', sa.Integer(), nullable=False),
    sa.Column('osis_id', sa.String(length=20), nullable=False),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomalies')
    # ### end Alembic commands ###

