"""add_word_cryptography_columns

Revision ID: 70aaac4d598a
Revises: e9e114f9080b
Create Date: 2026-06-25 01:20:39.561722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70aaac4d598a'
down_revision: Union[str, Sequence[str], None] = 'e9e114f9080b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('gematria_absolute', sa.Integer(), nullable=True))
    op.add_column('words', sa.Column('gematria_ordinal', sa.Integer(), nullable=True))
    op.add_column('words', sa.Column('gematria_reduced', sa.Integer(), nullable=True))
    op.add_column('words', sa.Column('atbash', sa.String(length=100), nullable=True))
    op.add_column('words', sa.Column('albam', sa.String(length=100), nullable=True))
    op.add_column('words', sa.Column('atbah', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'atbah')
    op.drop_column('words', 'albam')
    op.drop_column('words', 'atbash')
    op.drop_column('words', 'gematria_reduced')
    op.drop_column('words', 'gematria_ordinal')
    op.drop_column('words', 'gematria_absolute')
    # ### end Alembic commands ###
