"""add temple_dimensions table

Revision ID: 9d3588f7f7cc
Revises: 1700e9b98c6d
Create Date: 2026-06-26 17:02:25.058295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d3588f7f7cc'
down_revision: Union[str, Sequence[str], None] = '1700e9b98c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temple_dimensions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('osis_id', sa.String(length=20), nullable=False),
    sa.Column('object_name', sa.String(length=100), nullable=False),
    sa.Column('measurement_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['osis_id'], ['verses.osis_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temple_dimensions')
    # ### end Alembic commands ###
