"""Initial schema with pgvector

Revision ID: 9e25c54c5a54
Revises: 
Create Date: 2026-06-19 16:24:35.098026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '9e25c54c5a54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure vector extension is enabled before creating tables with vector columns
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osis_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('testament', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osis_code')
    )
    op.create_table('strongs_lexicon',
    sa.Column('strongs_number', sa.String(length=20), nullable=False),
    sa.Column('lemma', sa.String(length=50), nullable=False),
    sa.Column('transliteration', sa.String(length=50), nullable=True),
    sa.Column('pronunciation', sa.String(length=50), nullable=True),
    sa.Column('part_of_speech', sa.String(length=50), nullable=True),
    sa.Column('gloss', sa.String(length=200), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('strongs_number')
    )
    op.create_table('verses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('verse', sa.Integer(), nullable=False),
    sa.Column('osis_id', sa.String(length=20), nullable=False),
    sa.Column('hebrew_text', sa.Text(), nullable=True),
    sa.Column('english_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osis_id')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('bhs_sort', sa.Integer(), nullable=False),
    sa.Column('word_index', sa.Integer(), nullable=False),
    sa.Column('hebrew_segment', sa.String(length=100), nullable=False),
    sa.Column('transliteration', sa.String(length=100), nullable=True),
    sa.Column('strongs_number', sa.String(length=20), nullable=True),
    sa.Column('morph_code', sa.String(length=50), nullable=True),
    sa.Column('morph_detail', sa.Text(), nullable=True),
    sa.Column('english_gloss', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['strongs_number'], ['strongs_lexicon.strongs_number'], ),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bhs_sort')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    op.drop_table('verses')
    op.drop_table('strongs_lexicon')
    op.drop_table('books')
    # ### end Alembic commands ###
