"""add_is_public_to_saved_notes

Revision ID: b15ab639d5fa
Revises: dbad051a8b5a
Create Date: 2026-06-20 00:42:13.886964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15ab639d5fa'
down_revision: Union[str, Sequence[str], None] = 'dbad051a8b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_notes', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_notes', 'is_public')
    # ### end Alembic commands ###
