"""add_spatial_positions_to_saved_notes

Revision ID: e9e114f9080b
Revises: b15ab639d5fa
Create Date: 2026-06-20 00:56:09.592156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e114f9080b'
down_revision: Union[str, Sequence[str], None] = 'b15ab639d5fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_notes', sa.Column('x_position', sa.Integer(), nullable=True))
    op.add_column('saved_notes', sa.Column('y_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_notes', 'y_position')
    op.drop_column('saved_notes', 'x_position')
    # ### end Alembic commands ###
